# Generated by Django 3.2.9 on 2021-11-16 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=550, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('baseentity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.baseentity')),
                ('name', models.CharField(max_length=120)),
                ('full_description', models.TextField(blank=True, null=True)),
                ('current_stock', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('promotional_price', models.IntegerField(default=0)),
                ('tag', models.CharField(blank=True, max_length=10, null=True)),
                ('picture', models.ImageField(blank=True, default='avatar.png', upload_to='product/%Y/%m/%d')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.shop')),
            ],
            bases=('core.baseentity',),
        ),
        migrations.CreateModel(
            name='Sold',
            fields=[
                ('baseentity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.baseentity')),
                ('customer_fname', models.CharField(blank=True, max_length=550, null=True)),
                ('customer_email', models.CharField(blank=True, max_length=550, null=True)),
                ('customer_address', models.CharField(blank=True, max_length=550, null=True)),
                ('customer_lname', models.CharField(blank=True, max_length=550, null=True)),
                ('customer_phone', models.CharField(blank=True, max_length=550, null=True)),
                ('total_amount', models.CharField(blank=True, max_length=550, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='core.product')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.shop')),
            ],
            bases=('core.baseentity',),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('baseentity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.baseentity')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
                ('active', models.BooleanField(default=True)),
                ('products', models.ManyToManyField(null=True, to='core.Product')),
            ],
            bases=('core.baseentity',),
        ),
    ]
