# Generated by Django 3.2.9 on 2021-11-16 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sold',
            name='shop',
        ),
        migrations.AddField(
            model_name='sold',
            name='payment_method',
            field=models.CharField(blank=True, max_length=550, null=True),
        ),
        migrations.RemoveField(
            model_name='sold',
            name='prod',
        ),
        migrations.AddField(
            model_name='sold',
            name='prod',
            field=models.ManyToManyField(to='core.Product'),
        ),
    ]
